// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-dlHARiZgzrDkBtk1W7c8yP0ZIdBU5s4',
    appId: '1:590211221680:web:997786eba6f2a48ff89375',
    messagingSenderId: '590211221680',
    projectId: 'merhaba-app-b2b8c',
    authDomain: 'merhaba-app-b2b8c.firebaseapp.com',
    storageBucket: 'merhaba-app-b2b8c.firebasestorage.app',
    measurementId: 'G-XRDTRKXF9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlKdxbcFNvVe49YCiIWPZlnKLZUANnUB4',
    appId: '1:590211221680:android:529b4d925552375ef89375',
    messagingSenderId: '590211221680',
    projectId: 'merhaba-app-b2b8c',
    storageBucket: 'merhaba-app-b2b8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuGOcQxLfX7oz1R_ckR1yyFj67vM3-s-w',
    appId: '1:590211221680:ios:67bc6ca7b8db88ccf89375',
    messagingSenderId: '590211221680',
    projectId: 'merhaba-app-b2b8c',
    storageBucket: 'merhaba-app-b2b8c.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuGOcQxLfX7oz1R_ckR1yyFj67vM3-s-w',
    appId: '1:590211221680:ios:67bc6ca7b8db88ccf89375',
    messagingSenderId: '590211221680',
    projectId: 'merhaba-app-b2b8c',
    storageBucket: 'merhaba-app-b2b8c.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-dlHARiZgzrDkBtk1W7c8yP0ZIdBU5s4',
    appId: '1:590211221680:web:1b877a4401ddc6c3f89375',
    messagingSenderId: '590211221680',
    projectId: 'merhaba-app-b2b8c',
    authDomain: 'merhaba-app-b2b8c.firebaseapp.com',
    storageBucket: 'merhaba-app-b2b8c.firebasestorage.app',
    measurementId: 'G-WJNQ1ZD10M',
  );
}
